services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/train.py"]  # Command to run the training script
    volumes:
      - data:/workspace/data  # Named volume for training data
      - logs:/workspace/logs  # Named volume for logs

  infer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/infer.py"]
    depends_on:
      - train  # Specify that infer depends on train
    volumes:
      - data:/workspace/data  # Same volume for access to training data
      - logs:/workspace/logs  # Same volume for logs
      - output:/workspace/output  # Named volume for output

volumes:
  data:  # Define the named volume for data
  logs:  # Define the named volume for logs
  output:  # Define the named volume for output
